const CONFIRM_LEVELS = [1, 2, 3];
const DEFAULT_AI_CONFIDENCE = 0.5;
const MAX_AI_DISCOVERY_MESSAGE_LENGTH = 4000;
const MAX_STORED_MESSAGES = 50;

module.exports = {
  CONFIRM_LEVELS,
  DEFAULT_AI_CONFIDENCE,
  MAX_AI_DISCOVERY_MESSAGE_LENGTH,
  MAX_STORED_MESSAGES,
};
